INSERT INTO MARCA(NAME)
VALUES ('TOYOTA');
INSERT INTO MARCA(NAME)
VALUES ('VOLKSWAGEN');
INSERT INTO MARCA(NAME)
VALUES ('SEAT');

INSERT INTO COCHE (NAME, COLOR, MARCA_ID)
VALUES ('PASSAT', 'GRIS', SELECT ID FROM MARCA WHERE MARCA.NAME = 'VOLKSWAGEN');
INSERT INTO COCHE (NAME, COLOR, MARCA_ID)
VALUES ('CHR', 'AZUL', SELECT ID FROM MARCA WHERE MARCA.NAME = 'TOYOTA');
INSERT INTO COCHE (NAME, COLOR, MARCA_ID)
VALUES ('IBIZA', 'ROJO', SELECT ID FROM MARCA WHERE MARCA.NAME = 'SEAT');

INSERT INTO PRECIO (START_DATE, END_DATE, PRICE, COCHE_ID)
VALUES ('2020-01-01', '2020-05-20', 23000.20, SELECT ID FROM COCHE WHERE NAME = 'PASSAT');
INSERT INTO PRECIO (START_DATE, END_DATE, PRICE, COCHE_ID)
VALUES ('2020-05-21', '2020-12-31', 21000.20, SELECT ID FROM COCHE WHERE NAME = 'PASSAT');